class Insertar < ActiveRecord::Migration
  def self.up
    execute "insert into pastors(name,primary_last_name,second_last_name,date_of_birth,state) values('Irineo','Vargas',' ','10/10/2010',TRUE);"
    execute "insert into pastors(name,primary_last_name,second_last_name,date_of_birth,state) values('Paulino','Andia',' ','10/10/2010',TRUE);"
    execute "insert into pastors(name,primary_last_name,second_last_name,date_of_birth,state) values('Estanislao','Bofill',' ','10/10/2010',TRUE);"
    execute "insert into pastors(name,primary_last_name,second_last_name,date_of_birth,state) values('German','Sains',' ','10/10/2010',TRUE);"
    execute "insert into pastors(name,primary_last_name,second_last_name,date_of_birth,state) values('Alberto','Del Vecchio',' ','10/10/2010',TRUE);"
    execute "insert into pastors(name,primary_last_name,second_last_name,date_of_birth,state) values('Magno','Huanto',' ','10/10/2010',TRUE);"
    execute "insert into pastors(name,primary_last_name,second_last_name,date_of_birth,state) values('Philipus','Alek',' ','10/10/2010',TRUE);"
    execute "insert into pastors(name,primary_last_name,second_last_name,date_of_birth,state) values('Marcelo','Bazan',' ','10/10/2010',TRUE);"
    execute "insert into pastors(name,primary_last_name,second_last_name,date_of_birth,state) values('Sergio','Gamberoni',' ','10/10/2010',TRUE);"
    execute "insert into pastors(name,primary_last_name,second_last_name,date_of_birth,state) values('Jesus','Moreno',' ','10/10/2010',TRUE);"
    execute "insert into pastors(name,primary_last_name,second_last_name,date_of_birth,state) values('Wilson','Sejas',' ','10/10/2010',TRUE);"
    execute "insert into pastors(name,primary_last_name,second_last_name,date_of_birth,state) values('Fernando','Rojas','Silva','10/10/2010',TRUE);"
    execute "insert into pastors(name,primary_last_name,second_last_name,date_of_birth,state) values('Federico','Torrico',' ','10/10/2010',TRUE);"
    execute "insert into pastors(name,primary_last_name,second_last_name,date_of_birth,state) values('Hugo','Saravia',' ','10/10/2010',TRUE);"
    execute "insert into pastors(name,primary_last_name,second_last_name,date_of_birth,state) values('Txema','Martinez','De La Fuente','10/10/2010',TRUE);"
    execute "insert into pastors(name,primary_last_name,second_last_name,date_of_birth,state) values('Pastor','Pacsi',' ','10/10/2010',TRUE);"
    execute "insert into pastors(name,primary_last_name,second_last_name,date_of_birth,state) values('Cirilo','Aceituno',' ','10/10/2010',TRUE);"
    execute "insert into pastors(name,primary_last_name,second_last_name,date_of_birth,state) values('Wilson','Selinas',' ','10/10/2010',TRUE);"
    execute "insert into pastors(name,primary_last_name,second_last_name,date_of_birth,state) values('Antonio','Alcocer',' ','10/10/2010',TRUE);"
    execute "insert into pastors(name,primary_last_name,second_last_name,date_of_birth,state) values('Antonio','Chocarro',' ','10/10/2010',TRUE);"
    execute "insert into pastors(name,primary_last_name,second_last_name,date_of_birth,state) values('Armando','Sejas',' ','10/10/2010',TRUE);"
    execute "insert into pastors(name,primary_last_name,second_last_name,date_of_birth,state) values('Edwin','Quispe',' ','10/10/2010',TRUE);"
    execute "insert into pastors(name,primary_last_name,second_last_name,date_of_birth,state) values('Cleto','Hinojosa',' ','10/10/2010',TRUE);"
    execute "insert into pastors(name,primary_last_name,second_last_name,date_of_birth,state) values('Valerio','Modena',' ','10/10/2010',TRUE);"
    execute "insert into pastors(name,primary_last_name,second_last_name,date_of_birth,state) values('Fernando','Gallo',' ','10/10/2010',TRUE);"
    execute "insert into pastors(name,primary_last_name,second_last_name,date_of_birth,state) values('Francisco','Dardichon',' ','10/10/2010',TRUE);"
    execute "insert into pastors(name,primary_last_name,second_last_name,date_of_birth,state) values('Jesus E.','Osorno','Gil','10/10/2010',TRUE);"
    execute "insert into pastors(name,primary_last_name,second_last_name,date_of_birth,state) values('Jose','Senteno',' ','10/10/2010',TRUE);"
    execute "insert into pastors(name,primary_last_name,second_last_name,date_of_birth,state) values('Marco','Verberckt',' ','10/10/2010',TRUE);"
    execute "insert into pastors(name,primary_last_name,second_last_name,date_of_birth,state) values('Enrique','Zabala',' ','10/10/2010',TRUE);"
    execute "insert into pastors(name,primary_last_name,second_last_name,date_of_birth,state) values('Jaques','Delor',' ','10/10/2010',TRUE);"
    execute "insert into pastors(name,primary_last_name,second_last_name,date_of_birth,state) values('Jose','Gallo',' ','10/10/2010',TRUE);"
    execute "insert into pastors(name,primary_last_name,second_last_name,date_of_birth,state) values('Evar','Fernandez',' ','10/10/2010',TRUE);"
    execute "insert into pastors(name,primary_last_name,second_last_name,date_of_birth,state) values('Elio','Di Lenarda',' ','10/10/2010',TRUE);"
    execute "insert into pastors(name,primary_last_name,second_last_name,date_of_birth,state) values('Francisco','Gutierrez',' ','10/10/2010',TRUE);"
    execute "insert into pastors(name,primary_last_name,second_last_name,date_of_birth,state) values('Tomas','Mamani',' ','10/10/2010',TRUE);"
    execute "insert into pastors(name,primary_last_name,second_last_name,date_of_birth,state) values('Miguel Angel','Aymar',' ','10/10/2010',TRUE);"
    execute "insert into pastors(name,primary_last_name,second_last_name,date_of_birth,state) values('Javier','Ulunque',' ','10/10/2010',TRUE);"
    execute "insert into pastors(name,primary_last_name,second_last_name,date_of_birth,state) values('Juan','Guzman',' ','10/10/2010',TRUE);"
    execute "insert into pastors(name,primary_last_name,second_last_name,date_of_birth,state) values('Crispin','Borda',' ','10/10/2010',TRUE);"
    execute "insert into pastors(name,primary_last_name,second_last_name,date_of_birth,state) values('Massimo','Fratus',' ','10/10/2010',TRUE);"
    execute "insert into pastors(name,primary_last_name,second_last_name,date_of_birth,state) values('Alejo','Gerling',' ','10/10/2010',TRUE);"
    execute "insert into pastors(name,primary_last_name,second_last_name,date_of_birth,state) values('Paolo','Archetti',' ','10/10/2010',TRUE);"
    execute "insert into pastors(name,primary_last_name,second_last_name,date_of_birth,state) values('Carlos E.','Curiel','H.','10/10/2010',TRUE);"
    execute "insert into pastors(name,primary_last_name,second_last_name,date_of_birth,state) values('Simon','Leaño','Duchen','10/10/2010',TRUE);"
    execute "insert into pastors(name,primary_last_name,second_last_name,date_of_birth,state) values('Roberto','Caceres',' ','10/10/2010',TRUE);"
    execute "insert into pastors(name,primary_last_name,second_last_name,date_of_birth,state) values('Amado','Camacho',' ','10/10/2010',TRUE);"
    execute "insert into pastors(name,primary_last_name,second_last_name,date_of_birth,state) values('Sergio','Montes',' ','10/10/2010',TRUE);"
    execute "insert into pastors(name,primary_last_name,second_last_name,date_of_birth,state) values('Lazaro','Torrico',' ','10/10/2010',TRUE);"
    execute "insert into pastors(name,primary_last_name,second_last_name,date_of_birth,state) values('Felix','Parra',' ','10/10/2010',TRUE);"
    execute "insert into pastors(name,primary_last_name,second_last_name,date_of_birth,state) values('Marcial','Sanchez',' ','10/10/2010',TRUE);"
    execute "insert into pastors(name,primary_last_name,second_last_name,date_of_birth,state) values('Virgilio','Anturiano',' ','10/10/2010',TRUE);"
    execute "insert into pastors(name,primary_last_name,second_last_name,date_of_birth,state) values('Enrique','Bustamante',' ','10/10/2010',TRUE);"
    execute "insert into pastors(name,primary_last_name,second_last_name,date_of_birth,state) values('Lucio','Arnez',' ','10/10/2010',TRUE);"
    execute "insert into pastors(name,primary_last_name,second_last_name,date_of_birth,state) values('Antonio','Gil','Aguilera','10/10/2010',TRUE);"
    execute "insert into pastors(name,primary_last_name,second_last_name,date_of_birth,state) values('Rodolfo','Benavente',' ','10/10/2010',TRUE);"
    execute "insert into pastors(name,primary_last_name,second_last_name,date_of_birth,state) values('Victor','Benavente',' ','10/10/2010',TRUE);"
    execute "insert into pastors(name,primary_last_name,second_last_name,date_of_birth,state) values('Joaquin','Herbas',' ','10/10/2010',TRUE);"
    execute "insert into pastors(name,primary_last_name,second_last_name,date_of_birth,state) values('Walter','Rocha',' ','10/10/2010',TRUE);"
    execute "insert into pastors(name,primary_last_name,second_last_name,date_of_birth,state) values('Rodolfo','Ramirez',' ','10/10/2010',TRUE);"
    execute "insert into pastors(name,primary_last_name,second_last_name,date_of_birth,state) values('Francisco Pablo','Ross','Gallo','10/10/2010',TRUE);"
    execute "insert into pastors(name,primary_last_name,second_last_name,date_of_birth,state) values('Tomas','Flores',' ','10/10/2010',TRUE);"
    execute "insert into pastors(name,primary_last_name,second_last_name,date_of_birth,state) values('Manfredo','Rauh',' ','10/10/2010',TRUE);"
    execute "insert into pastors(name,primary_last_name,second_last_name,date_of_birth,state) values('Jhonny','Villarroel',' ','10/10/2010',TRUE);"
    execute "insert into pastors(name,primary_last_name,second_last_name,date_of_birth,state) values('Reynaldo','Acometa',' ','10/10/2010',TRUE);"
    execute "insert into pastors(name,primary_last_name,second_last_name,date_of_birth,state) values('Gregorio','Di Marchi',' ','10/10/2010',TRUE);"
    execute "insert into pastors(name,primary_last_name,second_last_name,date_of_birth,state) values('Mauro','Palamini',' ','10/10/2010',TRUE);"
    execute "insert into pastors(name,primary_last_name,second_last_name,date_of_birth,state) values('Misioneras De Jesus','V y Victima',' ','10/10/2010',TRUE);"
    execute "insert into pastors(name,primary_last_name,second_last_name,date_of_birth,state) values('Esperandio','Ravasio',' ','10/10/2010',TRUE);"    
  end

  def self.down
    execute "truncate table pastors"   
  end
end
